### ISSUE TITLE
Kirby kirbytextRaw Plugin

### ISSUE THREAD

**Issue by jenstornell** [getkirby/plugins#10]
**Github:** https://github.com/jbeyerstedt/kirby-plugin-kirbytextRaw

> Kirby Plugin to get kirbytext() without the enclosing `<p>`-tags

**Comment by jbeyerstedt** [comment]
@texnixe Is it possible to transfer this issue back to the Kirby 2 plugins? Because this plugin is useful in Kirby 2, but not for Kirby 3 any more (since Kirby 3.1.0).
And what's the plan anyway for plugins, which support Kirby 2 and 3? Should they have one issue in each of the plugin repositories?

**Comment by texnixe** [comment]
@jbeyerstedt Unfortunately not, transferring is only possible between repos within the same organization, it seems. I'd close this issue and create a new one in the K2 plugins repo.

**Comment by jbeyerstedt** [comment]
@texnixe I already (re-)created an issue in the K2 repo. But I have no rights to close this (and add the labels back to my other two plugins). Could you add me to the right group please?

Closing, because it's not needed for Kirby 3 any more. See https://github.com/getkirby-v2/plugins/issues/643 for the Kirby 2 version.
Or #61 (https://github.com/yoanmalie/kirbytextWrap) for a quite mature version, that supports both K2 and K3 in the same plugin.

**Comment by texnixe** [comment]
@jbeyerstedt I added you to the developer team.
