### ISSUE TITLE
Feed (plugin): lastBuildDate warning/error

### ISSUE THREAD

**Issue by jolantis** [getkirby/plugins#21]
The feed output does not validate, because (I believe since the Kirby 2.1 update) there's a date() error:

```
Warning:  date() expects parameter 2 to be long, string given in /var/www/v2.getkirby.com/site/plugins/feed/template.php on line 8
```

Validation output of **getkirby.com/blog/feed** can be seen here: http://j.mp/1FF0gJl

The issue has to do with this part in `plugins/feed/template.php`:

```
<lastBuildDate><?php echo date('r', $modified) ?></lastBuildDate>
```

Any ideas?

**Comment by servicethinker** [comment]
Have the same error. Here's a little workaround:

Search for `$modified` in line 8
Replace with `$items->first()->modified())`

This sets the lastModified date to the modified date of the first article. You can also use your `datefield` variable instead of `modified`.

**Comment by jolantis** [comment]
Thanks @servicethinker for your help!

I made this workaround for now:

```html
<lastBuildDate><?php echo $site->find($link)->modified('r'); ?></lastBuildDate>
```

In my case the `$link` variable is `'blog'`.

**Comment by lukasbestle** [comment]
The proper fix would be replacing `false` with `null` in [feed.php:40](https://github.com/getkirby/plugins/blob/master/feed/feed.php#L40).

**Comment by tech10** [comment]
Hi,
Line 40 of feed.php is referring to the options for particular items, not the build date.

I have also run into this error, and upon investigating, discovered two things. By default, the $modified variable available in the template is set in the defaults array in feed.php, and should be set to the value of time(). That would make sense, since the feed is dynamically built, it would be built when you accessed it. However, the $modified variable is set to an empty string instead. Here's another workaround that might be a little more accurate, and in my opinion, makes a little more sense.

In template.php, change the original line:

    <lastBuildDate><?php echo date('r', $modified) ?></lastBuildDate>

Add this instead.

    <lastBuildDate><?php echo date('r') ?></lastBuildDate>

In my opinion, the proper solution would be to figure out why the modified default option in feed.php is being set to an empty string and correct that. The above workaround I posted works well for me, though.

Blake

**Comment by lukasbestle** [comment]
Please see my comment above for the proper fix.

**Comment by tech10** [comment]
That worked, though I didn't think it would based on the Kirby docs and the cheetsheet. I didn't think null was a valid parameter to use, I knew false and a string were, though.

**Comment by lukasbestle** [comment]
Oh, that's an error in the docs. I will create a PR for that.

As you can see in [page.php:723](https://github.com/getkirby/kirby/blob/master/core/page.php#L723), the default param is `null`. But before getkirby/kirby@78473d149d42f4d9abe76981078b93ee62cff488, it didn't matter, because the method checked whether it was falsy or not. Now it actually checks for `null`.

**Comment by tech10** [comment]
Ah yes, I see that. Thanks for the info.
